/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_JniPlayground */

#ifndef _Included_org_example_JniPlayground
#define _Included_org_example_JniPlayground
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_JniPlayground
 * Method:    crashNow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_JniPlayground_crashNow
  (JNIEnv *, jobject);

/*
 * Class:     org_example_JniPlayground
 * Method:    allocate1KbMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_JniPlayground_allocate1KbMemory
  (JNIEnv *, jobject);

/*
 * Class:     org_example_JniPlayground
 * Method:    deepStackCrash
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_JniPlayground_deepStackCrash
  (JNIEnv *, jobject);

/*
 * Class:     org_example_JniPlayground
 * Method:    getStringLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_example_JniPlayground_getStringLength
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_example_JniPlayground
 * Method:    callBeanMethod
 * Signature: (Lorg/example/TestBean;)V
 */
JNIEXPORT void JNICALL Java_org_example_JniPlayground_callBeanMethod
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_example_JniPlayground
 * Method:    modifyBeanField
 * Signature: (Lorg/example/TestBean;)V
 */
JNIEXPORT void JNICALL Java_org_example_JniPlayground_modifyBeanField
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_example_JniPlayground
 * Method:    allocNativeStruct
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_example_JniPlayground_allocNativeStruct
  (JNIEnv *, jobject);

/*
 * Class:     org_example_JniPlayground
 * Method:    readNativeStruct
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_example_JniPlayground_readNativeStruct
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_example_JniPlayground
 * Method:    freeNativeStruct
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_example_JniPlayground_freeNativeStruct
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
